apiVersion: v1
kind: Service
metadata:
  name: securingweb
  namespace: securingweb
  labels:
    app: securingweb-app
spec:
  type: ClusterIP
  selector:
    app: securingweb-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http

